### ISSUE TITLE
Fix 'What We Do' menu nav toggle

### ISSUE THREAD

**Issue by kidwellington** [kidwellington/ventures#11]
The 'What We Do' link has a simple click event attached to it that toggles the view of its sub-navigation menu, as defined in `menu.component.ts`:

```js
toggle() {
    this.show = !this.show;
  }
```

This should be enhanced so that:
- clicking outside the expanded sub-nav also closes the menu
- navigating to a new view closes the sub-nav

**Comment by irishjp14** [comment]
This is a 2 part solution. 

Request 1 - clicking outside of the expanded menu will have to be handled at the app component layer and then triggering a function to check if there is an opened sub-nav.

Request 2 - navigating to a new view will be handled by adding toggle() function to the sub-nav a tags.
